### ISSUE TITLE
Sezioni a utenti

### ISSUE THREAD

**Issue by marcosegato** [FlatNuke/flatnuke-3#2]
_From @arpierm on July 12, 2016 7:40_

Esiste la possibilità di far modificare una sezione a piu utenti con l'editor wysiwyg ??

_Copied from original issue: FlatNuke/flatnuke#17_

**Comment by marcosegato** [comment]
Mi da questo errore quando tento di assegnare una sezione ad un utente registrato:
Fn_die: $mod is not a valid directory! functions.php: 3488

ho un sito con FN 3.1.5 su server ergonet.it

**Comment by marcosegato** [comment]
Non riesco a riprodurre l'errore, funziona correttamente sia su 3.1.5 (verificato direttamente online sul sito ufficiale) che su 4.x

**Comment by bebabi34** [comment]
il fatto che venga printato $mod indica che non viene assegnata correttamente la dir in precedenza. caratteri particolari nel nome sezione? versione php del server? messaggi di log?

**Comment by arpierm** [comment]
Indirizzo dell’Host: http://jolapiazza.com/index.php
Sistema operativo: Linux
Server web: Apache
Versione di PHP: 5.5.23 - PHPInfo
Versione librerie GD: 2.1.0
Versione di Flatnuke: 3.1.5

**Comment by arpierm** [comment]
Sono riuscito a sistemare mancava gli underscore nel titolo della sezione, però volevo sapere se c'è la possibilita di far creare, a l'utente abilitato, delle sottosezioni ?

**Comment by marcosegato** [comment]
@arpierm no non è possibile: l'utente amministratore (livello 10) è il solo a poter modificare la struttura del sito e quindi, ad esempio, a poter creare sottosezioni; un utente standard (livelli 0-9) abilitato alla modifica di una sezione ne può cambiare il contenuto e basta.

**Comment by arpierm** [comment]
Allora direi di chiudere ma prima ancora una domanda la versione 4 è affidabile e se si come fare per fare upgrade della 3.1.5 ?

**Comment by bebabi34** [comment]
di per sé è affidabile. la procedura di upgrade è ancora da
perfezionare. dai un'occhiata al file upgrade.php della 4 ;)

Il 27/07/2016 09:12, arpierm ha scritto:
