### ISSUE TITLE
flatnuke 3 su php 7.3

### ISSUE THREAD

**Issue by arpierm** [FlatNuke/flatnuke-3#5]
Buongiorno, ho u sito in flatnuke 3 e funziona bene con php 5.3 ma se cambio con php 7.3 per adesso, solo la sezione download mi da questo errore: Fatal error: 'continue' not in the 'loop' or 'switch' context in /........./download/include/phpfunctions/fd_vote_functions.php on line 208. 
Qualcuno sa come si può risolvere ?

**Comment by marcosegato** [comment]
Ciao, si tratta di una modifica introdotta da PHP 7.0 che restringe le casistiche di utilizzo di quel comando solo all'interno di loop.
Per correggere, è sufficiente sostituire "continue" con "return".
Nel caso ti capiti con altre pagine, puoi fare riferimento ai medesimi file della versione [corrente](https://github.com/FlatNuke/flatnuke) di Flatnuke per capire quali modifiche applicare. Flatnuke 3 non verrà modificato per supportare PHP 7.
